package com.brandonlenz.iso8583.definitions.fields.names;

public enum FieldName {
    MTI("Message Type Indicator (MTI)"),
    PRIMARY_BITMAP("Primary Bitmap"),
    SECONDARY_BITMAP("Secondary Bitmap"),
    TERTIARY_BITMAP("Tertiary Bitmap"),
    PRIMARY_ACCOUNT_NUMBER("Primary Account Number (PAN)"),
    PROCESSING_CODE("Processing Code"),
    AMOUNT_TRANSACTION("Amount, Transaction"),
    AMOUNT_SETTLEMENT("Amount, Settlement"),
    AMOUNT_CARDHOLDER_BILLING("Amount, Cardholder Billing"),
    TRANSMISSION_DATE_AND_TIME("Transmission Date & Time"),
    AMOUNT_CARDHOLDER_BILLING_FEE("Amount, Cardholder Billing Fee"),
    CONVERSION_RATE_SETTLEMENT("Conversion Rate, Settlement"),
    CONVERSION_RATE_CARDHOLDER_BILLING("Conversion Rate, Cardholder Billing"),
    SYSTEM_TRACE_AUDIT_NUMBER("System Trace Audit Number (STAN)"),
    LOCAL_TRANSACTION_TIME("Local Transaction Time (hhmmss)"),
    LOCAL_TRANSACTION_DATE("Local Transaction Date (MMDD)"),
    EXPIRATION_DATE("Expiration Date"),
    SETTLEMENT_DATE("Settlement Date"),
    CURRENCY_CONVERSION_DATE("Currency Conversion Date"),
    CAPTURE_DATE("Capture Date"),
    MERCHANT_CATEGORY_CODE("Merchant Category Code (MCC)"),
    ACQUIRING_INSTITUTION_COUNTRY_CODE("Acquiring Institution (Country Code)"),
    PAN_EXTENDED_COUNTRY_CODE("PAN Extended (Country Code)"),
    FORWARDING_INSTITUTION_COUNTRY_CODE("Forwarding Institution (Country Code)"),
    POINT_OF_SERVICE_ENTRY_MODE("Point of Service Entry Mode"),
    APPLICATION_PAN_SEQUENCE_NUMBER("Main PAN Sequence Number"),
    FUNCTION_CODE("Function Code"),
    POINT_OF_SERVICE_CONDITION_CODE("Point of Service Condition Code"),
    POINT_OF_SERVICE_CAPTURE_CODE("Point of Service Capture Code"),
    AUTHORIZING_IDENTIFICATION_RESPONSE_LENGTH("Authorizing Identification Response Length"),
    AMOUNT_TRANSACTION_FEE("Amount, Transaction Fee"),
    AMOUNT_SETTLEMENT_FEE("Amount, settlement Fee"),
    AMOUNT_TRANSACTION_PROCESSING_FEE("Amount, transaction Processing Fee"),
    AMOUNT_SETTLEMENT_PROCESSING_FEE("Amount, Settlement Processing Fee"),
    ACQUIRING_INSTITUTION_IDENTIFICATION_CODE("Acquiring Institution Identification Code"),
    FORWARDING_INSTITUTION_IDENTIFICATION_CODE("Forwarding Institution Identification Code"),
    PRIMARY_ACCOUNT_NUMBER_EXTENDED("Primary Account Number, Extended"),
    TRACK_2_DATA("Track 2 Data"),
    TRACK_3_DATA("Track 3 Data"),
    RETRIEVAL_REFERENCE_NUMBER("Retrieval Reference Number"),
    AUTHORIZATION_IDENTIFICATION_RESPONSE("Authorization Identification Response"),
    RESPONSE_CODE("Response Code"),
    SERVICE_RESTRICTION_CODE("Service Restriction Code"),
    CARD_ACCEPTOR_TERMINAL_IDENTIFICATION("Card Acceptor Terminal Identification"),
    CARD_ACCEPTOR_IDENTIFICATION_CODE("Card Acceptor Identification Code"),
    CARD_ACCEPTOR_NAME_AND_LOCATION("Card Acceptor Name/Location"),
    ADDITIONAL_RESPONSE_DATA("Additional Response Data"),
    TRACK_1_DATA("Track 1 Data"),
    ADDITIONAL_DATA_ISO("Additional Data (ISO)"),
    ADDITIONAL_DATA_NATIONAL("Additional Data (National)"),
    ADDITIONAL_DATA_PRIVATE("Additional Data (Private)"),
    CURRENCY_CODE_TRANSACTION("Currency Code, Transaction"),
    CURRENCY_CODE_SETTLEMENT("Currency Code, Settlement"),
    CURRENCY_CODE_CARDHOLDER_BILLING("Currency Code, Cardholder Billing"),
    PERSONAL_IDENTIFICATION_NUMBER_DATA("Personal Identification Number Data"),
    SECURITY_RELATED_CONTROL_INFORMATION("Security Related Control Information"),
    ADDITIONAL_AMOUNTS("Additional Amounts"),
    ICC_DATA("ICC data"),
    RESERVED_ISO("Reserved (ISO)"),
    RESERVED_NATIONAL("Reserved (National)"),
    RESERVED_PRIVATE("Reserved (Private)"),
    MESSAGE_AUTHENTICATION_CODE("Message Authentication Code (MAC)"),
    EXTENDED_BITMAP_INDICATOR("Extended Bitmap Indicator"),
    SETTLEMENT_CODE("Settlement Code"),
    EXTENDED_PAYMENT_CODE("Extended Payment Code"),
    RECEIVING_INSTITUTION_COUNTRY_CODE("Receiving Institution Country Code"),
    SETTLEMENT_INSTITUTION_COUNTRY_CODE("Settlement Institution country Code"),
    NETWORK_MANAGEMENT_INFORMATION_CODE("Network Management Information Code"),
    MESSAGE_NUMBER("Message Number"),
    LAST_MESSAGES_NUMBER("Last Message's Number"),
    ACTION_DATE("Action Date (YYMMDD)"),
    NUMBER_OF_CREDITS("Number of Credits"),
    CREDITS_REVERSAL_NUMBER("Credits, Reversal Number"),
    NUMBER_OF_DEBITS("Number of Debits"),
    DEBITS_REVERSAL_NUMBER("Debits, Reversal Number"),
    TRANSFER_NUMBER("Transfer Number"),
    TRANSFER_REVERSAL_NUMBER("Transfer, Reversal Number"),
    NUMBER_OF_INQUIRIES("Number of Inquiries"),
    NUMBER_OF_AUTHORIZATIONS("Number of Authorizations"),
    CREDITS_PROCESSING_FEE_AMOUNT("Credits, Processing Fee Amount"),
    CREDITS_TRANSACTION_FEE_AMOUNT("Credits, Transaction Fee Amount"),
    DEBITS_PROCESSING_FEE_AMOUNT("Debits, Processing Fee Amount"),
    DEBITS_TRANSACTION_FEE_AMOUNT("Debits, Transaction Fee Amount"),
    TOTAL_AMOUNT_OF_CREDITS("Total Amount of Credits"),
    CREDITS_REVERSAL_AMOUNT("Credits, Reversal Amount"),
    TOTAL_AMOUNT_OF_DEBITS("Total Amount of Debits"),
    DEBITS_REVERSAL_AMOUNT("Debits, Reversal Amount"),
    ORIGINAL_DATA_ELEMENTS("Original Data Elements"),
    FILE_UPDATE_CODE("File Update Code"),
    FILE_SECURITY_CODE("File Security Code"),
    RESPONSE_INDICATOR("Response Indicator"),
    SERVICE_INDICATOR("Service Indicator"),
    REPLACEMENT_AMOUNTS("Replacement Amounts"),
    MESSAGE_SECURITY_CODE("Message Security Code"),
    NET_SETTLEMENT_AMOUNT("Net Settlement Amount"),
    PAYEE("Payee"),
    SETTLEMENT_INSTITUTION_IDENTIFICATION_CODE("Settlement Institution Identification Code"),
    RECEIVING_INSTITUTION_IDENTIFICATION_CODE("Receiving Institution Identification Code"),
    FILE_NAME("File Name"),
    ACCOUNT_IDENTIFICATION_1("Account Identification 1"),
    ACCOUNT_IDENTIFICATION_2("Account Identification 2"),
    TRANSACTION_DESCRIPTION("Transaction Description"),

    VARIABLE_LENGTH_INDICATOR("VLI");


    private String name;

    FieldName(String name) {
        this.name = name;
    }

    public String getName() {
        return name;
    }
}
